# Generated by Django 5.2.4 on 2025-08-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
