# Generated by Django 5.2.4 on 2025-07-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_job_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
