# Generated by Django 5.2.4 on 2025-08-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_manager_name': 'objects'},
        ),
    ]
