# Generated by Django 5.2.4 on 2025-08-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_milestone_approve_only_if_milestone_completed'),
        ('job', '0004_remove_milestone_approve_only_if_milestone_completed_and_more'),
    ]

    operations = [
    ]
