# Generated by Django 5.2.4 on 2025-08-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_merge_20250806_0509'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='milestone',
            name='approve_only_if_milestone_completed',
        ),
    ]
