# Generated by Django 5.2.4 on 2025-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_merge_20250806_0917'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(('is_approved_by_employer', False), ('is_completed_by_freelancer', True), _connector='OR'), name='approve_only_if_milestone_completed'),
        ),
    ]
