# Generated by Django 5.2.4 on 2025-08-06 10:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_milestone_approve_only_if_milestone_completed_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='milestone',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='milestone_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
