# Generated by Django 5.2.4 on 2025-08-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_milestone_approve_only_if_milestone_completed'),
        ('job', '0010_milestone_milestone_title_trgm'),
    ]

    operations = [
    ]
